// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXlL0fnfrDu8ZtwEyqlvj3N6DSG41efk',
    appId: '1:762369467211:web:d9e78cb608aa7cb9eb3ece',
    messagingSenderId: '762369467211',
    projectId: 'budget-app-fb214',
    authDomain: 'budget-app-fb214.firebaseapp.com',
    storageBucket: 'budget-app-fb214.firebasestorage.app',
    measurementId: 'G-VWBZ7HLCJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XHn8p446iNOqAh2aWumMNt5rtwnJWnc',
    appId: '1:762369467211:android:670d618cac185cb0eb3ece',
    messagingSenderId: '762369467211',
    projectId: 'budget-app-fb214',
    storageBucket: 'budget-app-fb214.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLxwqNOjnZoILxmVqkz2dMhadCV5ueDiQ',
    appId: '1:762369467211:ios:8168153da6c5d37beb3ece',
    messagingSenderId: '762369467211',
    projectId: 'budget-app-fb214',
    storageBucket: 'budget-app-fb214.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );
}
